std = "roblox"
exclude = ["Packages/*", "src/Packages/*", "src/t.luau", "src/spr.luau"]

[lints]
multiple_statements = "allow"
shadowing = "warn"
unused_variable = "warn"
global_usage = "allow"