--Generated by the forest wally mirror. Re-exports the package's root module.
local MODULE = require(script["src"])
export type Status = MODULE.Status
export type ErrorKind = MODULE.ErrorKind
export type Error = MODULE.Error
export type Promise = MODULE.Promise
export type TypedPromise<T...> = MODULE.TypedPromise<T...>
export type PromiseStatic = MODULE.PromiseStatic
return MODULE
