--Generated by the forest wally mirror. Wally-style sibling link.
local MODULE = require(script.Parent.Packages["Promise"])
export type Status = MODULE.Status
export type ErrorKind = MODULE.ErrorKind
export type Error = MODULE.Error
export type Promise = MODULE.Promise
export type TypedPromise<T...> = MODULE.TypedPromise<T...>
export type PromiseStatic = MODULE.PromiseStatic
return MODULE
